'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ua' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ua: {
    // Header
    langUA: 'UA',
    langEN: 'EN',
    
    // Sidebar
    dashboard: 'Дашборд',
    chats: 'Чати',
    calendar: 'Календар',
    calculator: 'Калькулятор',
    
    // Dashboard
    usersCount: 'Кількість користувачів',
    chatsCount: 'Кількість чатів',
    activeChats: 'Активні чати',
    perWeek: 'за тиждень',
    selectSession: 'Виберіть сесію для перегляду деталей',
    
    // Chat
    selectChat: 'Виберіть чат',
    chatWith: 'Чат з',
    generateReport: 'Згенерувати звіт',
    selectSessionToStart: 'Виберіть сесію для початку чату',
    selectClientFromList: 'Оберіть клієнта зі списку зліва для перегляду повідомлень',
    loading: 'Завантаження...',
    sessionNotFound: 'Сесію не знайдено',
    noMessages: 'Немає повідомлень у цій сесії',
    noMessagesInSession: 'Немає повідомлень',
    client: 'Клієнт',
    manager: 'Менеджер',
    ai: 'AI',
    noText: '(без тексту)',
    generatingReport: 'Генерується звіт…',
    
    // SalesChatView
    chat: 'Чат',
    autoSummary: 'Auto-summary',
    estimate: 'Estimate',
    researchHighlights: 'Research Highlights',
    notEnoughData: 'Недостатньо даних',
    generatingSummary: 'Генерується summary...',
    generatingEstimate: 'Генерується estimate...',
    generatingHighlights: 'Генерується highlights...',
    
    // Calendar
    monday: 'Понеділник',
    tuesday: 'Вівторок',
    wednesday: 'Середа',
    thursday: 'Четвер',
    friday: 'Пʼятниця',
    saturday: 'Субота',
    sunday: 'Неділя',
    month: 'Місяць',
    week: 'Тиждень',
    day: 'День',
    year: 'Рік',
    january: 'січень',
    february: 'лютий',
    march: 'березень',
    april: 'квітень',
    may: 'травень',
    june: 'червень',
    july: 'липень',
    august: 'серпень',
    september: 'вересень',
    october: 'жовтень',
    november: 'листопад',
    december: 'грудень',
    weekRange: 'Тиждень',
    
    // Auth
    signIn: 'Увійти',
    signUp: 'Зареєструватися',
    signOut: 'Вийти',
    email: 'Email',
    password: 'Пароль',
    confirmPassword: 'Підтвердіть пароль',
    signInWithGoogle: 'Увійти через Google',
    signUpWithGoogle: 'Зареєструватися через Google',
    signInToAccount: 'Увійти в обліковий запис',
    createAccount: 'Створити обліковий запис',
    passwordsDoNotMatch: 'Паролі не співпадають',
    failedToSignIn: 'Помилка входу. Перевірте дані.',
    failedToSignUp: 'Помилка реєстрації. Спробуйте ще раз.',
    user: 'Користувач',
    
    // Calculator
    '%': '%',
    'CE': 'CE',
    'C': 'C',
    '/': '/',
    '7': '7',
    '8': '8',
    '9': '9',
    '*': '*',
    '4': '4',
    '5': '5',
    '6': '6',
    '-': '-',
    '1': '1',
    '2': '2',
    '3': '3',
    '+': '+',
    '0': '0',
    '.': '.',
    '=': '=',
    '(': '(',
    ')': ')',
    'π': 'π',
    'e': 'e',
    'sin': 'sin',
    'cos': 'cos',
    'tan': 'tan',
    '√': '√',
    'ln': 'ln',
    'log': 'log',
    'x²': 'x²',
    'xʸ': 'xʸ',
    'ans': 'ans',
    'EXP': 'EXP',
    
    // Table/Reports
    latestSessions: 'Останні сесії',
    searchByName: 'Пошук по імені...',
    name: "Ім'я",
    status: 'Статус',
    createdAt: 'Дата створення',
    messages: 'Повідомлень',
    noSessions: 'Немає сесій',
    // Short weekdays
    monShort: 'Пн',
    tueShort: 'Вт',
    wedShort: 'Ср',
    thuShort: 'Чт',
    friShort: 'Пт',
    satShort: 'Сб',
    sunShort: 'Нд',
    progressToGoals: 'Прогрес до цілей',
    goalFor: 'Ціль за',
    current: 'Поточний результат',
    left: 'Залишилось',
    of: 'з',
    per: 'за',
    goalReached: 'Ціль досягнута!',
    almostThere: 'Майже досягнуто!',
    keepGoing: 'Продовжуй!',
    goodProgress: 'Гарний прогрес!',
    strongStart: 'Сильний старт!',
    timeToAct: 'Час діяти!',
    read: 'Прочитано',
    unread: 'Непрочитано',
    searchEventsPlaceholder: 'Пошук подій...',
    addEvent: 'Додати подію',
    newEvent: 'Нова подія',
    eventName: 'Назва події',
    eventNamePlaceholder: 'Введіть назву події',
    eventDate: 'Дата',
    eventTime: 'Година',
    eventDescription: 'Опис',
    eventDescriptionPlaceholder: 'Опис події',
    save: 'Зберегти',
    cancel: 'Скасувати',
    inactive: 'Неактивна',
    active: 'Активна',
    completed: 'Завершена',
    archived: 'Архівована',
    assistant: 'AI помічник',
    welcomeCiedenAI: 'Вітаємо у Cieden AI',
    assistantDescription: 'AI-асистент для менеджерів з продажу: генеруйте листи, аналізуйте угоди, знаходьте клієнтів, готуйте скрипти та підвищуйте ефективність роботи.',
    history: 'Історія',
    clearHistory: 'Очистити всю історію',
    newChat: '+ Новий чат',
    historyEmpty: 'Історія порожня',
    createFirstChat: 'Створіть перший чат',
    inputPlaceholder: 'Запитайте що-небудь...',
    // --- AI Assistant Example Prompts ---
    salesAnalysisTitle: 'Аналіз продажів',
    salesAnalysisPrompt: 'Допоможи проаналізувати продажі за останній місяць. Які тренди ти помічаєш?',
    salesStrategyTitle: 'Стратегія продажів',
    salesStrategyPrompt: 'Розкажи про ефективні стратегії продажів для B2B сегменту',
    objectionHandlingTitle: 'Обробка обʼєкцій',
    objectionHandlingPrompt: 'Як краще відповідати на обʼєкцію “Це занадто дорого”?',
    productPresentationTitle: 'Презентація продукту',
    productPresentationPrompt: 'Допоможи скласти презентацію для потенційного клієнта',
    negotiationTitle: 'Ведення переговорів',
    negotiationPrompt: 'Які техніки ведення переговорів найефективніші?',
    planningTitle: 'Планування',
    planningPrompt: 'Допоможи скласти план роботи на тиждень для менеджера з продажу',
  },
  en: {
    // Header
    langUA: 'UA',
    langEN: 'EN',
    
    // Sidebar
    dashboard: 'Dashboard',
    chats: 'Chats',
    calendar: 'Calendar',
    calculator: 'Calculator',
    
    // Dashboard
    usersCount: 'Users Count',
    chatsCount: 'Chats Count',
    activeChats: 'Active Chats',
    perWeek: 'per week',
    selectSession: 'Select session to view details',
    
    // Chat
    selectChat: 'Select Chat',
    chatWith: 'Chat with',
    generateReport: 'Generate Report',
    selectSessionToStart: 'Select session to start chat',
    selectClientFromList: 'Choose client from left list to view messages',
    loading: 'Loading...',
    sessionNotFound: 'Session not found',
    noMessages: 'No messages in this session',
    noMessagesInSession: 'No messages',
    client: 'Client',
    manager: 'Manager',
    ai: 'AI',
    noText: '(no text)',
    generatingReport: 'Generating report...',
    
    // SalesChatView
    chat: 'Chat',
    autoSummary: 'Auto-summary',
    estimate: 'Estimate',
    researchHighlights: 'Research Highlights',
    notEnoughData: 'Not enough data',
    generatingSummary: 'Generating summary...',
    generatingEstimate: 'Generating estimate...',
    generatingHighlights: 'Generating highlights...',
    
    // Calendar
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    month: 'Month',
    week: 'Week',
    day: 'Day',
    year: 'Year',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    weekRange: 'Week',
    
    // Auth
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    signInWithGoogle: 'Sign in with Google',
    signUpWithGoogle: 'Sign up with Google',
    signInToAccount: 'Sign in to your account',
    createAccount: 'Create your account',
    passwordsDoNotMatch: 'Passwords do not match',
    failedToSignIn: 'Failed to sign in. Please check your credentials.',
    failedToSignUp: 'Failed to register. Please try again.',
    user: 'User',
    
    // Calculator
    '%': '%',
    'CE': 'CE',
    'C': 'C',
    '/': '/',
    '7': '7',
    '8': '8',
    '9': '9',
    '*': '*',
    '4': '4',
    '5': '5',
    '6': '6',
    '-': '-',
    '1': '1',
    '2': '2',
    '3': '3',
    '+': '+',
    '0': '0',
    '.': '.',
    '=': '=',
    '(': '(',
    ')': ')',
    'π': 'π',
    'e': 'e',
    'sin': 'sin',
    'cos': 'cos',
    'tan': 'tan',
    '√': '√',
    'ln': 'ln',
    'log': 'log',
    'x²': 'x²',
    'xʸ': 'xʸ',
    'ans': 'ans',
    'EXP': 'EXP',
    
    // Table/Reports
    latestSessions: 'Latest sessions',
    searchByName: 'Search by name...',
    name: 'Name',
    status: 'Status',
    createdAt: 'Created at',
    messages: 'Messages',
    noSessions: 'No sessions',
    // Short weekdays
    monShort: 'Mon',
    tueShort: 'Tue',
    wedShort: 'Wed',
    thuShort: 'Thu',
    friShort: 'Fri',
    satShort: 'Sat',
    sunShort: 'Sun',
    progressToGoals: 'Progress to Goals',
    goalFor: 'Goal for',
    current: 'Current',
    left: 'Left',
    of: 'of',
    per: 'per',
    goalReached: 'Goal reached!',
    almostThere: 'Almost there!',
    keepGoing: 'Keep going!',
    goodProgress: 'Good progress!',
    strongStart: 'Strong start!',
    timeToAct: 'Time to act!',
    read: 'Read',
    unread: 'Unread',
    searchEventsPlaceholder: 'Search events...',
    addEvent: 'Add event',
    newEvent: 'New event',
    eventName: 'Event name',
    eventNamePlaceholder: 'Enter event name',
    eventDate: 'Date',
    eventTime: 'Time',
    eventDescription: 'Description',
    eventDescriptionPlaceholder: 'Event description',
    save: 'Save',
    cancel: 'Cancel',
    inactive: 'Inactive',
    active: 'Active',
    completed: 'Completed',
    archived: 'Archived',
    assistant: 'AI Assistant',
    welcomeCiedenAI: 'Welcome to Cieden AI',
    assistantDescription: 'AI assistant for sales managers: generate emails, analyze deals, find clients, prepare scripts, and boost your efficiency.',
    history: 'History',
    clearHistory: 'Clear all history',
    newChat: '+ New chat',
    historyEmpty: 'History is empty',
    createFirstChat: 'Create your first chat',
    inputPlaceholder: 'Ask something...',
    // --- AI Assistant Example Prompts ---
    salesAnalysisTitle: 'Sales Analysis',
    salesAnalysisPrompt: 'Help analyze sales for the last month. What trends do you notice?',
    salesStrategyTitle: 'Sales Strategy',
    salesStrategyPrompt: 'Tell me about effective sales strategies for the B2B segment',
    objectionHandlingTitle: 'Objection Handling',
    objectionHandlingPrompt: 'How to best respond to the objection “It’s too expensive”?',
    productPresentationTitle: 'Product Presentation',
    productPresentationPrompt: 'Help prepare a presentation for a potential client',
    negotiationTitle: 'Negotiation',
    negotiationPrompt: 'What are the most effective negotiation techniques?',
    planningTitle: 'Planning',
    planningPrompt: 'Help create a weekly work plan for a sales manager',
  }
};

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ua');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ua] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}; 