'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ua' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ua: {
    // Header
    langUA: 'UA',
    langEN: 'EN',
    
    // Sidebar
    dashboard: 'Дашборд',
    chats: 'Чати',
    calendar: 'Календар',
    calculator: 'Калькулятор',
    
    // Dashboard
    usersCount: 'Кількість користувачів',
    chatsCount: 'Кількість чатів',
    activeChats: 'Активні чати',
    perWeek: 'за тиждень',
    selectSession: 'Виберіть сесію для перегляду деталей',
    more: 'Більше',
    
    // Chat
    selectChat: 'Виберіть чат',
    chatWith: 'Чат з',
    generateReport: 'Згенерувати звіт',
    showReport: 'Показати звіт',
    selectSessionToStart: 'Виберіть сесію для початку чату',
    selectClientFromList: 'Оберіть клієнта зі списку зліва для перегляду повідомлень',
    loading: 'Завантаження...',
    sessionNotFound: 'Сесію не знайдено',
    noMessages: 'Немає повідомлень у цій сесії',
    noMessagesInSession: 'Немає повідомлень',
    client: 'Клієнт',
    manager: 'Менеджер',
    ai: 'AI',
    noText: '(без тексту)',
    generatingReport: 'Генерується звіт…',
    analyzingSession: 'Аналізуємо сесію...',
    generatingInsights: 'Генеруємо інсайти...',
    
    // Session Details
    sessionInformation: 'Інформація про сесію',
    sessionId: 'ID сесії',
    clientName: 'Клієнт',
    messagesCount: 'Кількість повідомлень',
    noData: 'Немає даних',
    webDevelopment: 'Веб-розробка',
    mobileDevelopment: 'Мобільна розробка',
    uiUxDesign: 'UI/UX дизайн',
    lowComplexity: 'Низька складність',
    mediumComplexity: 'Середня складність',
    highComplexity: 'Висока складність',
    userAuthentication: 'Авторизація користувачів',
    calculatorFeature: 'Калькулятор',
    productCatalog: 'Каталог продуктів',
    paymentIntegration: 'Інтеграція платежів',
    pushNotifications: 'Push-сповіщення',
    basicDevelopment: 'Базова розробка',
    clientRequirementsAnalyzed: 'Проаналізовано вимоги клієнта',
    technicalSolutionsProposed: 'Запропоновано технічні рішення',
    designRecommendations: 'Рекомендації по дизайну',
    functionalityDiscussed: 'Обговорено функціональність',
    clientNeedsIdentified: 'Визначено потреби клієнта',
    budgetConsiderations: 'Розглянуто бюджетні питання',
    timelineDiscussed: 'Обговорено терміни',
    technologyStackDiscussed: 'Обговорено технологічний стек',
    exportOptions: 'Експорт',
    emailDraft: 'Email чернетка',
    
    // SalesChatView
    chat: 'Чат',
    autoSummary: 'Auto-summary',
    estimate: 'Estimate',
    researchHighlights: 'Research Highlights',
    notEnoughData: 'Недостатньо даних',
    generatingSummary: 'Генерується summary...',
    generatingEstimate: 'Генерується estimate...',
    generatingHighlights: 'Генерується highlights...',
    
    // Calendar
    monday: 'Понеділник',
    tuesday: 'Вівторок',
    wednesday: 'Середа',
    thursday: 'Четвер',
    friday: 'Пʼятниця',
    saturday: 'Субота',
    sunday: 'Неділя',
    month: 'Місяць',
    week: 'Тиждень',
    day: 'День',
    year: 'Рік',
    january: 'січень',
    february: 'лютий',
    march: 'березень',
    april: 'квітень',
    may: 'травень',
    june: 'червень',
    july: 'липень',
    august: 'серпень',
    september: 'вересень',
    october: 'жовтень',
    november: 'листопад',
    december: 'грудень',
    weekRange: 'Тиждень',
    
    // Auth
    signIn: 'Увійти',
    signUp: 'Зареєструватися',
    signOut: 'Вийти',
    email: 'Email',
    password: 'Пароль',
    confirmPassword: 'Підтвердіть пароль',
    signInWithGoogle: 'Увійти через Google',
    signUpWithGoogle: 'Зареєструватися через Google',
    signInToAccount: 'Увійти в обліковий запис',
    createAccount: 'Створити обліковий запис',
    passwordsDoNotMatch: 'Паролі не співпадають',
    failedToSignIn: 'Помилка входу. Перевірте дані.',
    failedToSignUp: 'Помилка реєстрації. Спробуйте ще раз.',
    user: 'Користувач',
    
    // Calculator
    '%': '%',
    'CE': 'CE',
    'C': 'C',
    '/': '/',
    '7': '7',
    '8': '8',
    '9': '9',
    '*': '*',
    '4': '4',
    '5': '5',
    '6': '6',
    '-': '-',
    '1': '1',
    '2': '2',
    '3': '3',
    '+': '+',
    '0': '0',
    '.': '.',
    '=': '=',
    '(': '(',
    ')': ')',
    'π': 'π',
    'e': 'e',
    'sin': 'sin',
    'cos': 'cos',
    'tan': 'tan',
    '√': '√',
    'ln': 'ln',
    'log': 'log',
    'x²': 'x²',
    'xʸ': 'xʸ',
    'ans': 'ans',
    'EXP': 'EXP',
    
    // Table/Reports
    latestSessions: 'Останні сесії',
    searchByName: 'Пошук по імені...',
    name: "Ім'я",
    status: 'Статус',
    createdAt: 'Дата створення',
    messages: 'Повідомлень',
    noSessions: 'Немає сесій',
    // Short weekdays
    monShort: 'Пн',
    tueShort: 'Вт',
    wedShort: 'Ср',
    thuShort: 'Чт',
    friShort: 'Пт',
    satShort: 'Сб',
    sunShort: 'Нд',
    progressToGoals: 'Прогрес до цілей',
    goalFor: 'Ціль за',
    current: 'Поточний результат',
    left: 'Залишилось',
    of: 'з',
    per: 'за',
    goalReached: 'Ціль досягнута!',
    almostThere: 'Майже досягнуто!',
    keepGoing: 'Продовжуй!',
    goodProgress: 'Гарний прогрес!',
    strongStart: 'Сильний старт!',
    timeToAct: 'Час діяти!',
    read: 'Прочитано',
    unread: 'Непрочитано',
    searchEventsPlaceholder: 'Пошук подій...',
    addEvent: 'Додати подію',
    newEvent: 'Нова подія',
    eventName: 'Назва події',
    eventNamePlaceholder: 'Введіть назву події',
    eventDate: 'Дата',
    eventTime: 'Година',
    eventDescription: 'Опис',
    eventDescriptionPlaceholder: 'Опис події',
    save: 'Зберегти',
    cancel: 'Скасувати',
    inactive: 'Неактивна',
    active: 'Активна',
    completed: 'Завершена',
    archived: 'Архівована',
    assistant: 'AI помічник',
    welcomeCiedenAI: 'Вітаємо у Cieden AI',
    assistantDescription: 'AI-асистент для менеджерів з продажу: генеруйте листи, аналізуйте угоди, знаходьте клієнтів, готуйте скрипти та підвищуйте ефективність роботи.',
    history: 'Історія',
    clearHistory: 'Очистити всю історію',
    newChat: '+ Новий чат',
    historyEmpty: 'Історія порожня',
    createFirstChat: 'Створіть перший чат',
    inputPlaceholder: 'Запитайте що-небудь...',
    popularPrompts: 'Популярні запити',
    // --- AI Assistant Example Prompts ---
    salesAnalysisTitle: 'Аналіз продажів',
    salesAnalysisPrompt: 'Допоможи проаналізувати продажі за останній місяць. Які тренди ти помічаєш?',
    salesStrategyTitle: 'Стратегія продажів',
    salesStrategyPrompt: 'Розкажи про ефективні стратегії продажів для B2B сегменту',
    objectionHandlingTitle: 'Обробка обʼєкцій',
    objectionHandlingPrompt: 'Як краще відповідати на обʼєкцію “Це занадто дорого”?',
    productPresentationTitle: 'Презентація продукту',
    productPresentationPrompt: 'Допоможи скласти презентацію для потенційного клієнта',
    negotiationTitle: 'Ведення переговорів',
    negotiationPrompt: 'Які техніки ведення переговорів найефективніші?',
    planningTitle: 'Планування',
    planningPrompt: 'Допоможи скласти план роботи на тиждень для менеджера з продажу',
    
    // Session Details Popup
    sessionDetails: 'Session Details',
    createdDate: 'Created',
    totalMessages: 'Total messages',
    generatingSummaryAndEstimate: 'Генеруємо зведення та оцінку проекту',
    
    // Analysis Results
    insufficientDataForSummary: 'Недостатньо даних для генерації зведення',
    insufficientDataForEstimate: 'Недостатньо даних для оцінки',
    insufficientDataForAnalysis: 'Недостатньо даних для аналізу',
    waitingForClientResponses: 'Очікування відповідей від клієнта',
    
    // Project Types
    mobileApp: 'мобільний додаток',
    mobileAppDevelopment: 'розробка мобільного додатку для iOS та/або Android',
    website: 'веб-сайт',
    websiteDevelopment: 'створення веб-сайту або веб-додатку',
    streamingPlatform: 'платформа для стрімерів',
    streamingPlatformDevelopment: 'розробка платформи для відео-стрімінгу та взаємодії з аудиторією',
    ecommercePlatform: 'e-commerce платформа',
    ecommercePlatformDevelopment: 'створення онлайн-магазину з системою платежів',
    aiMlProject: 'AI/ML проект',
    aiMlDevelopment: 'розробка системи з використанням штучного інтелекту',
    softwareProduct: 'програмний продукт',
    softwareDevelopment: 'розробка програмного рішення',
    
    // Complexity Levels
    medium: 'Середня',
    high: 'Висока',
    veryHigh: 'Дуже висока',
    
    // Time Estimates
    timeEstimate2to3: '2-3 місяці',
    timeEstimate3to4: '3-4 місяці',
    timeEstimate3to5: '3-5 місяців',
    timeEstimate4to6: '4-6 місяців',
    timeEstimate6to9: '6-9 місяців',
    timeEstimate8to12: '8-12 місяців',
    
    // Services
    servicesUxUiDevelopmentTesting: 'UX/UI дизайн, розробка, тестування',
    servicesAiMlUxUiIntegrationTesting: 'AI/ML розробка, UX/UI дизайн, інтеграція, тестування',
    servicesVideoUxUiServerTesting: 'Відео-розробка, UX/UI дизайн, серверна частина, тестування',
    servicesFinancialUxUiSecurityTesting: 'Фінансова розробка, UX/UI дизайн, безпека, тестування',
    servicesMobileUxUiTestingPublishing: 'Мобільна розробка, UX/UI дизайн, тестування, публікація',
    servicesEcommerceUxUiPaymentIntegration: 'E-commerce розробка, UX/UI дизайн, інтеграція платежів',
    
    // Analysis Text
    clientInterestedIn: 'Клієнт зацікавлений у',
    specialAttentionToUxUi: 'Особлива увага до UX/UI дизайну та користувацького досвіду.',
    competitiveAdvantagesDefined: 'Визначені конкурентні переваги та цільова аудиторія.',
    projectHasScalingPotential: 'Проект має потенціал для масштабування.',
    approximateDevelopmentTime: 'Приблизний час розробки',
    complexity: 'Складність',
    budget: 'Бюджет',
    services: 'Послуги',
    
    // Highlights
    targetAudienceDefined: 'Визначена цільова аудиторія та користувачі',
    competitorAnalysisConducted: 'Проведений аналіз конкурентів та ринку',
    technicalArchitectureDefined: 'Визначена технічна архітектура та вимоги',
    budgetDiscussed: 'Обговорений бюджет та фінансові аспекти',
    timelineDefined: 'Визначені терміни та етапи розробки',
    scalingPlanDefined: 'План масштабування та розвитку продукту',
    specialAttentionToDesign: 'Особлива увага до дизайну та користувацького досвіду',
    needToDetailRequirements: 'Потрібно деталізувати вимоги та цілі проекту',
    
    // AI Notes
    clientActivelyInteracts: 'Клієнт активно взаємодіє та надає детальну інформацію',
    hasClearVision: 'Має чітке бачення продукту та його призначення',
    understandsCompetitiveAdvantages: 'Розуміє конкурентні переваги та цільову аудиторію',
    valuesQualityDesign: 'Цінує якісний дизайн та користувацький досвід',
    thinksAboutFuture: 'Думає про майбутнє та масштабування проекту',
    needToDiscussBudget: 'Потрібно обговорити бюджет та фінансування',
    needToDefineTimeline: 'Визначити терміни та етапи проекту',
    needMoreInformation: 'Потрібно більше інформації для детального аналізу',
    
    // Export Buttons
    exportPDF: 'Експорт PDF',
    exportCSV: 'Експорт CSV',
    exportExcel: 'Експорт Excel',
    generateEmailDraft: 'Згенерувати email-чернетку',
  },
  en: {
    // Header
    langUA: 'UA',
    langEN: 'EN',
    
    // Sidebar
    dashboard: 'Dashboard',
    chats: 'Chats',
    calendar: 'Calendar',
    calculator: 'Calculator',
    
    // Dashboard
    usersCount: 'Users Count',
    chatsCount: 'Chats Count',
    activeChats: 'Active Chats',
    perWeek: 'per week',
    selectSession: 'Select session to view details',
    more: 'More',
    
    // Chat
    selectChat: 'Select Chat',
    chatWith: 'Chat with',
    generateReport: 'Generate Report',
    showReport: 'Show Report',
    selectSessionToStart: 'Select session to start chat',
    selectClientFromList: 'Choose client from left list to view messages',
    loading: 'Loading...',
    sessionNotFound: 'Session not found',
    noMessages: 'No messages in this session',
    noMessagesInSession: 'No messages',
    client: 'Client',
    manager: 'Manager',
    ai: 'AI',
    noText: '(no text)',
    generatingReport: 'Generating report...',
    analyzingSession: 'Analyzing session...',
    generatingInsights: 'Generating insights...',
    
    // SalesChatView
    chat: 'Chat',
    autoSummary: 'Auto-summary',
    estimate: 'Estimate',
    researchHighlights: 'Research Highlights',
    notEnoughData: 'Not enough data',
    generatingSummary: 'Generating summary...',
    generatingEstimate: 'Generating estimate...',
    generatingHighlights: 'Generating highlights...',
    
    // Calendar
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    month: 'Month',
    week: 'Week',
    day: 'Day',
    year: 'Year',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    weekRange: 'Week',
    
    // Auth
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    signInWithGoogle: 'Sign in with Google',
    signUpWithGoogle: 'Sign up with Google',
    signInToAccount: 'Sign in to your account',
    createAccount: 'Create your account',
    passwordsDoNotMatch: 'Passwords do not match',
    failedToSignIn: 'Failed to sign in. Please check your credentials.',
    failedToSignUp: 'Failed to register. Please try again.',
    user: 'User',
    
    // Calculator
    '%': '%',
    'CE': 'CE',
    'C': 'C',
    '/': '/',
    '7': '7',
    '8': '8',
    '9': '9',
    '*': '*',
    '4': '4',
    '5': '5',
    '6': '6',
    '-': '-',
    '1': '1',
    '2': '2',
    '3': '3',
    '+': '+',
    '0': '0',
    '.': '.',
    '=': '=',
    '(': '(',
    ')': ')',
    'π': 'π',
    'e': 'e',
    'sin': 'sin',
    'cos': 'cos',
    'tan': 'tan',
    '√': '√',
    'ln': 'ln',
    'log': 'log',
    'x²': 'x²',
    'xʸ': 'xʸ',
    'ans': 'ans',
    'EXP': 'EXP',
    
    // Table/Reports
    latestSessions: 'Latest sessions',
    searchByName: 'Search by name...',
    name: 'Name',
    status: 'Status',
    createdAt: 'Created at',
    messages: 'Messages',
    noSessions: 'No sessions',
    // Short weekdays
    monShort: 'Mon',
    tueShort: 'Tue',
    wedShort: 'Wed',
    thuShort: 'Thu',
    friShort: 'Fri',
    satShort: 'Sat',
    sunShort: 'Sun',
    progressToGoals: 'Progress to Goals',
    goalFor: 'Goal for',
    current: 'Current',
    left: 'Left',
    of: 'of',
    per: 'per',
    goalReached: 'Goal reached!',
    almostThere: 'Almost there!',
    keepGoing: 'Keep going!',
    goodProgress: 'Good progress!',
    strongStart: 'Strong start!',
    timeToAct: 'Time to act!',
    read: 'Read',
    unread: 'Unread',
    searchEventsPlaceholder: 'Search events...',
    addEvent: 'Add event',
    newEvent: 'New event',
    eventName: 'Event name',
    eventNamePlaceholder: 'Enter event name',
    eventDate: 'Date',
    eventTime: 'Time',
    eventDescription: 'Description',
    eventDescriptionPlaceholder: 'Event description',
    save: 'Save',
    cancel: 'Cancel',
    inactive: 'Inactive',
    active: 'Active',
    completed: 'Completed',
    archived: 'Archived',
    assistant: 'AI Assistant',
    welcomeCiedenAI: 'Welcome to Cieden AI',
    assistantDescription: 'AI assistant for sales managers: generate emails, analyze deals, find clients, prepare scripts, and boost your efficiency.',
    history: 'History',
    clearHistory: 'Clear all history',
    newChat: '+ New chat',
    historyEmpty: 'History is empty',
    createFirstChat: 'Create your first chat',
    inputPlaceholder: 'Ask something...',
    popularPrompts: 'Popular Prompts',
    // --- AI Assistant Example Prompts ---
    salesAnalysisTitle: 'Sales Analysis',
    salesAnalysisPrompt: 'Help analyze sales for the last month. What trends do you notice?',
    salesStrategyTitle: 'Sales Strategy',
    salesStrategyPrompt: 'Tell me about effective sales strategies for the B2B segment',
    objectionHandlingTitle: 'Objection Handling',
    objectionHandlingPrompt: 'How to best respond to the objection “It’s too expensive”?',
    productPresentationTitle: 'Product Presentation',
    productPresentationPrompt: 'Help prepare a presentation for a potential client',
    negotiationTitle: 'Negotiation',
    negotiationPrompt: 'What are the most effective negotiation techniques?',
    planningTitle: 'Planning',
    planningPrompt: 'Help create a weekly work plan for a sales manager',
    
    // Session Details Popup
    sessionInformation: 'Session Information',
    sessionId: 'Session ID',
    clientName: 'Client',
    messagesCount: 'Messages count',
    noData: 'No data',
    webDevelopment: 'Web Development',
    mobileDevelopment: 'Mobile Development',
    uiUxDesign: 'UI/UX Design',
    lowComplexity: 'Low Complexity',
    mediumComplexity: 'Medium Complexity',
    highComplexity: 'High Complexity',
    userAuthentication: 'User Authentication',
    calculatorFeature: 'Calculator',
    productCatalog: 'Product Catalog',
    paymentIntegration: 'Payment Integration',
    pushNotifications: 'Push Notifications',
    basicDevelopment: 'Basic Development',
    clientRequirementsAnalyzed: 'Client Requirements Analyzed',
    technicalSolutionsProposed: 'Technical Solutions Proposed',
    designRecommendations: 'Design Recommendations',
    functionalityDiscussed: 'Functionality Discussed',
    clientNeedsIdentified: 'Client Needs Identified',
    budgetConsiderations: 'Budget Considerations',
    timelineDiscussed: 'Timeline Discussed',
    technologyStackDiscussed: 'Technology Stack Discussed',
    exportOptions: 'Export',
    emailDraft: 'Email Draft',
    sessionDetails: 'Session Details',
    createdDate: 'Created',
    totalMessages: 'Total messages',
    generatingSummaryAndEstimate: 'Generating summary and project estimate',
    
    // Analysis Results
    insufficientDataForSummary: 'Insufficient data for summary generation',
    insufficientDataForEstimate: 'Insufficient data for estimate',
    insufficientDataForAnalysis: 'Insufficient data for analysis',
    waitingForClientResponses: 'Waiting for client responses',
    
    // Project Types
    mobileApp: 'mobile app',
    mobileAppDevelopment: 'development of mobile app for iOS and/or Android',
    website: 'website',
    websiteDevelopment: 'creation of website or web application',
    streamingPlatform: 'streaming platform',
    streamingPlatformDevelopment: 'development of video streaming platform and audience interaction',
    ecommercePlatform: 'e-commerce platform',
    ecommercePlatformDevelopment: 'creation of online store with payment system',
    aiMlProject: 'AI/ML project',
    aiMlDevelopment: 'development of system using artificial intelligence',
    softwareProduct: 'software product',
    softwareDevelopment: 'development of software solution',
    
    // Complexity Levels
    medium: 'Medium',
    high: 'High',
    veryHigh: 'Very High',
    
    // Time Estimates
    timeEstimate2to3: '2-3 months',
    timeEstimate3to4: '3-4 months',
    timeEstimate3to5: '3-5 months',
    timeEstimate4to6: '4-6 months',
    timeEstimate6to9: '6-9 months',
    timeEstimate8to12: '8-12 months',
    
    // Services
    servicesUxUiDevelopmentTesting: 'UX/UI design, development, testing',
    servicesAiMlUxUiIntegrationTesting: 'AI/ML development, UX/UI design, integration, testing',
    servicesVideoUxUiServerTesting: 'Video development, UX/UI design, server-side, testing',
    servicesFinancialUxUiSecurityTesting: 'Financial development, UX/UI design, security, testing',
    servicesMobileUxUiTestingPublishing: 'Mobile development, UX/UI design, testing, publishing',
    servicesEcommerceUxUiPaymentIntegration: 'E-commerce development, UX/UI design, payment integration',
    
    // Analysis Text
    clientInterestedIn: 'Client is interested in',
    specialAttentionToUxUi: 'Special attention to UX/UI design and user experience.',
    competitiveAdvantagesDefined: 'Competitive advantages and target audience defined.',
    projectHasScalingPotential: 'Project has scaling potential.',
    approximateDevelopmentTime: 'Approximate development time',
    complexity: 'Complexity',
    budget: 'Budget',
    services: 'Services',
    
    // Highlights
    targetAudienceDefined: 'Target audience and users defined',
    competitorAnalysisConducted: 'Competitor and market analysis conducted',
    technicalArchitectureDefined: 'Technical architecture and requirements defined',
    budgetDiscussed: 'Budget and financial aspects discussed',
    timelineDefined: 'Timeline and development stages defined',
    scalingPlanDefined: 'Product scaling and development plan',
    specialAttentionToDesign: 'Special attention to design and user experience',
    needToDetailRequirements: 'Need to detail requirements and project goals',
    
    // AI Notes
    clientActivelyInteracts: 'Client actively interacts and provides detailed information',
    hasClearVision: 'Has clear vision of the product and its purpose',
    understandsCompetitiveAdvantages: 'Understands competitive advantages and target audience',
    valuesQualityDesign: 'Values quality design and user experience',
    thinksAboutFuture: 'Thinks about the future and project scaling',
    needToDiscussBudget: 'Need to discuss budget and financing',
    needToDefineTimeline: 'Need to define timeline and project stages',
    needMoreInformation: 'Need more information for detailed analysis',
    
    // Export Buttons
    exportPDF: 'Export PDF',
    exportCSV: 'Export CSV',
    exportExcel: 'Export Excel',
    generateEmailDraft: 'Generate email draft',
  }
};

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ua');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ua] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}; 